#!/bin/bash

frametitle=$@

cat <<EOF | xsel -ib

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\\begin{frame}
\\frametitle{${frametitle}}

\\begin{examples}{blah}
\\begin{itemize}
\\item
\\item
\\item
\\end{itemize}
\\end{examples}

\\end{frame}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

EOF
echo "... copied to clipboard"
